name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Summarize coverage
        run: |
          go tool cover -func=coverage.out -o=coverage.txt
          total=$(grep '^total:' coverage.txt | awk '{print $3}')
          echo "COVERAGE=${total}" >> $GITHUB_ENV
          echo "Coverage: ${total}" >> $GITHUB_STEP_SUMMARY

      - name: Generate coverage badge
        if: github.ref == 'refs/heads/main'
        uses: tj-actions/coverage-badge-go@v2
        with:
          filename: coverage.out
          output: coverage.svg

      - name: Commit coverage badge
        if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update coverage badge
          file_pattern: coverage.svg


